.TH TPOP3D 8
.\"
.\" tpop3d.8: manual page for tpop3d
.\"
.\" Copyright (c) 2001 Chris Lightfoot. All rights reserved.
.\"
.\" $Id$
.\"

.\" Text begins
.SH NAME
tpop3d \- small, fast, extensible POP3 server
.SH SYNOPSIS
.B tpop3d
.B \-h
| [
.B \-f
.I file
] [
.B \-p
.I file
] [
.B \-d
] [
.B \-v
]
.SH DESCRIPTION
\fBtpop3d\fP is a server which implements the RFC1939 POP3 protocol, including
UIDL support. \fBtpop3d\fP supports virtual domain authentication via a number
of mechanisms, POP-before-SMTP relaying, TCP wrappers, Maildir mailboxes and
various other useful features.  It is a daemon which waits in the background
and accepts incoming connections. It cannot be operated from \fBinetd\fP(8).

\fBtpop3d\fP logs most diagnostics via \fBsyslog\fP(3), using facility
\fBmail\fP or another which is defined in its configuration file.

Detailed control over the operation of \fBtpop3d\fP is exercised by editing its
configuration file, by default \fB/etc/tpop3d.conf\fP. See the manual entry for
\fBtpop3d.conf\fP(5) for more information.

.SH OPTIONS

.TP
.B -h
Print a summary of usage and the compile-time options of this \fBtpop3d\fP.
.TP
\fB-f\fP \fIfile\fP
Read configuration from \fIfile\fP, instead of from \fB/etc/tpop3d.conf\fP.
.TP
\fB-p\fP \fIfile\fP
Write the PID of the server process to \fIfile\fP. By default, no PID file is
written.
.TP
.B -d
Do not fork to become a daemon, but stay attached to a controlling terminal
and print log messages to standard error as well as the syslog
.TP
.B -v
Log traffic being sent to/from the server, for debugging purposes; \fBtpop3d\fP
will log commands and responses sent, but not passwords or the actual content
of messages.

.SH SIGNALS

.TP
\fBSIGTERM\fP, \fBSIGINT\fP
Cause the daemon to exit, closing any active connections.
.TP
\fBSIGHUP\fP
Cause the daemon to restart, re-reading its configuration file. This will not close
active connections which have already been authenticated.
.TP
other signals
Most other signals are ignored, though some (\fBSIGSEGV\fP etc.) will cause the
daemon to terminate prematurely. In these circumstances, \fBtpop3d\fP should
clear up all of its lock files. However, if this happens, it indicates either
a bug in \fBtpop3d\fP, or a hardware problem. In the former case, please
contact me (see below for contact details) with information about your
configuration and (if known) steps which may be taken to reproduce the bug.
In particular, the configuration options which you used to compile \fBtpop3d\fP
and the operating system and version under which you are running it are
essential information for a bug report.

.SH BUGS

Locking of mailspools under Unix is problematic, mostly because of past
brokenness which has now been fixed. \fBtpop3d\fP's locking scheme should
suffice in most cases (and should work reliably over NFS) but it is naive: it
locks the mailspool for exclusive access, so that an MTA cannot
deliver mail to the mailspool whilst it is being accessed by a \fBtpop3d\fP
user. As a result, it is configured by default to time out users rather
rapidly (after 30s of inactivity). This is one of several places where it is
marginally noncompliant with RFC1939. Note that the locking issues do not
apply to maildir mailboxes.

Authentication drivers block the main daemon; this means that a failure in NIS
or an external program could prevent \fBtpop3d\fP from handling new
connections. A future version may support asynchronous authentication drivers.

If TCP Wrappers support is enabled, then reverse-DNS resolution of connected
client addresses may also block the main daemon.

.SH FILES

.B /etc/tpop3d.conf

.SH SEE ALSO

.BR tpop3d.conf (5),
.BR exim (8),
.BR inetd (8),
.BR syslog (3),
.BR mysql (1),
.BR TPOP3D::AuthDriver (1),
.BR RFC1939,
.br
.IR http://www.ex-parrot.com/~chris/tpop3d/ ,
.br
.IR http://www.ex-parrot.com/~chris/vmail-sql/ ,
.br
.IR http://www.mysql.com/ ,
.br
.IR http://lists.beasts.org/pipermail/tpop3d-discuss/ .

.SH AUTHOR
Chris Lightfoot <chris@ex-parrot.com>. Portions by Mark Longair and Paul
Makepeace.

If you have a query about \fBtpop3d\fP, \fIplease do not send me personal
email\fP. Instead, please send it to the \fBtpop3d\fP mailing list, to which
you can subscribe by sending an email with the subject `subscribe' to
.br
<tpop3d-discuss-request@lists.beasts.org>. There is a mailing list archive
at
.br
.IR http://lists.beasts.org/pipermail/tpop3d-discuss/ .

.SH VERSION

$Id$

.SH COPYING
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

